In [1]:
%cd /kaggle/working

!pip -q install -U transformers sentencepiece spacy scikit-learn pandas tqdm nltk pytorch-lightning
!python -m spacy download en_core_web_sm -q

!rm -rf /kaggle/working/AlignScore
!git clone https://github.com/yuh-zha/AlignScore.git /kaggle/working/AlignScore

# Patch 1: AdamW issue
MODEL_FILE = "/kaggle/working/AlignScore/src/alignscore/model.py"

with open(MODEL_FILE, "r", encoding="utf-8") as f:
    code = f.read()

code = code.replace(
    "from transformers import AdamW, get_linear_schedule_with_warmup, AutoConfig",
    "from torch.optim import AdamW\nfrom transformers import get_linear_schedule_with_warmup, AutoConfig"
)

with open(MODEL_FILE, "w", encoding="utf-8") as f:
    f.write(code)

# Patch 2: pytorch_lightning load_from_checkpoint issue
INFER_FILE = "/kaggle/working/AlignScore/src/alignscore/inference.py"

with open(INFER_FILE, "r", encoding="utf-8") as f:
    code = f.read()

code = code.replace(
    "self.model = BERTAlignModel(model=model).load_from_checkpoint(checkpoint_path=ckpt_path, strict=False).to(self.device)",
    "self.model = BERTAlignModel.load_from_checkpoint(checkpoint_path=ckpt_path, model=model, strict=False).to(self.device)"
)

with open(INFER_FILE, "w", encoding="utf-8") as f:
    f.write(code)

import sys
sys.path.insert(0, "/kaggle/working/AlignScore/src")

from alignscore.alignscore import AlignScore

print("AlignScore ready ✅")

/kaggle/working
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 99.1 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 92.9 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 101.1 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 44.7 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 43.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 97.0 MB/s eta 0:00:00:00:010:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
ydata-profiling 4.18.4 requires numba<0.63,>=0.60, but you have numba 0.65.1 which is incompatible.
ydata-profiling 4.18.4 requires numpy<2.4,>=1.22, but you have numpy 2.4.6 which is incompatible.
ydata-profiling 4.18.4 requires pandas!=1.4.0,<3.0,>1.5, but you have pandas 3.0.3 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.3 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 45.1 MB/s eta 0:00:0000:010:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Cloning into '/kaggle/working/AlignScore'...
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 202 (delta 36), reused 12 (delta 12), pack-reused 153 (from 1)
Receiving objects: 100% (202/202), 523.86 KiB | 14.16 MiB/s, done.
Resolving deltas: 100% (113/113), done.
AlignScore ready ✅

In [2]:
import os

CKPT_PATH = "/kaggle/working/AlignScore-base.ckpt"

if not os.path.exists(CKPT_PATH):
    !wget -q -O /kaggle/working/AlignScore-base.ckpt https://huggingface.co/yzha/AlignScore/resolve/main/AlignScore-base.ckpt

print("Checkpoint exists:", os.path.exists(CKPT_PATH))

Checkpoint exists: True

In [3]:
import os
import torch
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report, confusion_matrix

INPUT_CSV = "/kaggle/input/datasets/belalheshamfathy/oragnai/test_predictions _oragnail.csv"
OUTPUT_DIR = "/kaggle/working/alignscore_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

BATCH_SIZE = 8
DEVICE = 0 if torch.cuda.is_available() else -1
THRESHOLDS = [0.30, 0.40, 0.50, 0.60, 0.70]

df = pd.read_csv(INPUT_CSV)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

df = df.dropna(subset=["knowledge", "question", "answer", "label"]).reset_index(drop=True)
df["label"] = df["label"].astype(int)

contexts = (
    "Knowledge:\n" + df["knowledge"].astype(str) +
    "\n\nQuestion:\n" + df["question"].astype(str)
).tolist()

claims = df["answer"].astype(str).tolist()
labels = df["label"].values

scorer = AlignScore(
    model="roberta-base",
    batch_size=BATCH_SIZE,
    device=DEVICE,
    ckpt_path=CKPT_PATH,
    evaluation_mode="nli_sp"
)

scores = []

for i in tqdm(range(0, len(contexts), BATCH_SIZE), desc="AlignScore scoring"):
    batch_scores = scorer.score(
        contexts=contexts[i:i+BATCH_SIZE],
        claims=claims[i:i+BATCH_SIZE]
    )
    scores.extend(batch_scores)

scores = np.array(scores, dtype=float)
df["alignscore"] = scores

results = []

for th in THRESHOLDS:
    preds = (scores >= th).astype(int)

    acc = accuracy_score(labels, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        preds,
        average="binary",
        pos_label=1,
        zero_division=0
    )

    cm = confusion_matrix(labels, preds)

    results.append({
        "method": "AlignScore",
        "threshold": th,
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "tn": cm[0, 0],
        "fp": cm[0, 1],
        "fn": cm[1, 0],
        "tp": cm[1, 1],
    })

results_df = pd.DataFrame(results).sort_values("f1", ascending=False)

BEST_THRESHOLD = float(results_df.iloc[0]["threshold"])
final_preds = (scores >= BEST_THRESHOLD).astype(int)

df["alignscore_prediction"] = final_preds
df["alignscore_correct"] = df["alignscore_prediction"] == df["label"]

df.to_csv(f"{OUTPUT_DIR}/alignscore_predictions.csv", index=False)
results_df.to_csv(f"{OUTPUT_DIR}/alignscore_threshold_results.csv", index=False)

precision, recall, f1, _ = precision_recall_fscore_support(
    labels,
    final_preds,
    average="binary",
    pos_label=1,
    zero_division=0
)

final_summary = pd.DataFrame([{
    "method": "AlignScore",
    "best_threshold": BEST_THRESHOLD,
    "accuracy": accuracy_score(labels, final_preds),
    "precision": precision,
    "recall": recall,
    "f1": f1,
    "num_samples": len(df)
}])

final_summary.to_csv(f"{OUTPUT_DIR}/alignscore_final_summary.csv", index=False)

print("\nThreshold Results:")
display(results_df)

print("\nBest Threshold:", BEST_THRESHOLD)

print("\nClassification Report:")
print(classification_report(
    labels,
    final_preds,
    target_names=["Hallucinated", "Supported"],
    zero_division=0
))

print("\nConfusion Matrix:")
print(confusion_matrix(labels, final_preds))

print("\nFinal Summary:")
display(final_summary)

print("\nSaved in:", OUTPUT_DIR)

Shape: (6000, 6)
Columns: ['knowledge', 'question', 'answer', 'label', 'prediction', 'correct']

Lightning automatically upgraded your loaded checkpoint from v1.7.7 to v2.6.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint AlignScore-base.ckpt`
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-base
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/core/saving.py:197: Found keys that are not in the model state dict but in the checkpoint: ['base_model.embeddings.position_ids']

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

AlignScore scoring:   0%|          | 0/750 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  12%|█▎        | 1/8 [00:00<00:04,  1.52it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:01,  4.64it/s]
Evaluating:  62%|██████▎   | 5/8 [00:00<00:00,  7.22it/s]
Evaluating: 100%|██████████| 8/8 [00:01<00:00,  7.76it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 29.21it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.98it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.73it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.75it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.67it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.82it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.91it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.57it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.45it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.73it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.63it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.48it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.47it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.70it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.53it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.26it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.49it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.39it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.95it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.54it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.82it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.60it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.43it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.85it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.35it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.52it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.61it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.95it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.56it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.58it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.71it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.81it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.31it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.34it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.79it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.44it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.55it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.41it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.62it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.27it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.18it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.44it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.04it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.12it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.54it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.84it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.40it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.02it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.30it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.69it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.90it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.47it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.42it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.71it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.15it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.51it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.41it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.00it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.02it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.60it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.01it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.52it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.56it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.15it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.68it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.63it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 21.43it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 24.49it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.47it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.57it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.70it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.37it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.24it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 24.67it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.37it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.29it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.49it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.83it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.23it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.41it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.48it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.70it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.24it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.84it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.39it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.15it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.33it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.13it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.00it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.36it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.73it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.28it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.24it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.96it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.26it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.94it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.25it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.05it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.29it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.08it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.62it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.63it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.44it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.14it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.62it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.41it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.02it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.16it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.20it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.12it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.95it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.91it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.68it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.00it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.41it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.52it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.54it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.18it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.86it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.91it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.08it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 24.49it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.38it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.06it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 21.35it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 24.23it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.45it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.24it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.68it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.26it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 21.17it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 24.25it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.38it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.31it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.50it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.09it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.57it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.24it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.43it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 24.00it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.32it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.48it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.88it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.92it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.92it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.02it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.46it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.65it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.22it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.86it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.02it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.81it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.63it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.64it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.96it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.94it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.10it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.18it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.78it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.18it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.87it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.42it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.52it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.76it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.32it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.98it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.93it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.54it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.56it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 27.10it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.79it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.92it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.70it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.84it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.37it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.62it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.65it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.66it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.93it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.97it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.74it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.80it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.01it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.77it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.07it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.72it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.21it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.75it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.22it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.77it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.10it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.80it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.18it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.65it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.71it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.62it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.12it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.46it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.23it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.96it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.33it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.53it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.86it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.78it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.63it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.42it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.47it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.57it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.74it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.89it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.45it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.94it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.28it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.36it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 28.00it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 24.09it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.02it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.47it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.37it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.72it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.48it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.89it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.24it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 24.18it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 25.99it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.34it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.73it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.64it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.82it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.73it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.16it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.77it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 26.62it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.45it/s]

Evaluating:   0%|          | 0/8 [00:00<?, ?it/s]
Evaluating:  38%|███▊      | 3/8 [00:00<00:00, 27.39it/s]
Evaluating: 100%|██████████| 8/8 [00:00<00:00, 26.24it/s]


Threshold Results:

,method,threshold,accuracy,precision,recall,f1,tn,fp,fn,tp
0,AlignScore,0.3,0.770833,0.722664,0.879000,0.793202,1988,1012,363,2637
1,AlignScore,0.4,0.770333,0.736581,0.841667,0.785625,2097,903,475,2525
2,AlignScore,0.5,0.760500,0.745677,0.790667,0.767513,2191,809,628,2372
3,AlignScore,0.6,0.743167,0.753916,0.722000,0.737613,2293,707,834,2166
4,AlignScore,0.7,0.714833,0.755653,0.635000,0.690092,2384,616,1095,1905

Best Threshold: 0.3

Classification Report:
              precision    recall  f1-score   support

Hallucinated       0.85      0.66      0.74      3000
   Supported       0.72      0.88      0.79      3000

    accuracy                           0.77      6000
   macro avg       0.78      0.77      0.77      6000
weighted avg       0.78      0.77      0.77      6000


Confusion Matrix:
[[1988 1012]
 [ 363 2637]]

Final Summary:

,method,best_threshold,accuracy,precision,recall,f1,num_samples
0,AlignScore,0.3,0.770833,0.722664,0.879,0.793202,6000

Saved in: /kaggle/working/alignscore_outputs